services:
  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    container_name: users-service
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - app-network
    restart: unless-stopped

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production
      - PORT=3002
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
